### ISSUE TITLE
app.start()

### ISSUE THREAD

**Issue by pradt** [NativeScript/template-blank-ng#45]
Hi,
I was expecting to find a initialisation command such as app.start () but I didn't see this in this template. Where does the app start from (especially if I want to enter firebase initialisation steps) ?

**Comment by manoldonev** [comment]
app.start() command is the initialization command for non-Angular templates (check app.ts [here](https://github.com/NativeScript/template-blank-ts/blob/release/app.ts) and app.js [here](https://github.com/NativeScript/template-blank/blob/release/app.js)). Initialization logic for Angular templates can be found in the respective [main.ts](https://github.com/NativeScript/template-blank-ng/blob/release/main.ts) / [main.aot.ts](https://github.com/NativeScript/template-blank-ng/blob/release/main.aot.ts). 

You can also check the Angular master/detail template with Firebase for sample Firebase initialization steps [here](https://github.com/NativeScript/template-master-detail-ng). Alternatively you can find the non-Angular master/detail with Firebase templates [here](https://github.com/NativeScript/template-master-detail-ts) and [here](https://github.com/NativeScript/template-master-detail).

**Comment by pradt** [comment]
Thanks @manoldonev
