### ISSUE TITLE
JS: Analytics: Sending statistics

### ISSUE THREAD

**Issue by FranciZ** [NativeScript/template-blank-ng#51]
From a fresh install I get this repeating message in the terminal:

```
JS: Analytics: Sending statistics
JS: Analytics: Failed sending statistics
```

This template also takes an unusual amount of time to boot the app. The [template-drawer-navigation-ng](https://github.com/NativeScript/template-drawer-navigation-ng) boots much faster and does not produce the messages above.

**Comment by MartoYankov** [comment]
@FranciZ This looks like a log from the [NativeScript Analytics Plugin](https://market.nativescript.org/plugins/nativescript-telerik-analytics). The templates don't have this plugin set up, so it's strange that you see this log. Is it possible that your app has the plugin somehow? Or probably another app running on this device?
